controller_manager:
  ros__parameters:
    update_rate: 50 # Aumentamos para 50Hz para ter um movimento bem fluido

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - wrist_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - gripper_joint1
    interface_name: position
    command_interfaces:
      - position